
services:
    db:
        image: mysql:5.7
        container_name: mysql_c
        volumes:
            - db-volume:/var/lib/mysql
            - ./articles.sql:/docker-entrypoint-initdb.d/articles.sql
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        ports:
            - "3306:3306"

        deploy: 
            mode: replicated
            replicas: 3
            

    app:
        build: .
        image: myapp
        container_name: myapp_c
        volumes:
            - ./app:/var/www/html
        ports:
            - 8080:80
        depends_on:
            - db
        

        
        

volumes:
    db-volume: